In [1]:
import numpy as np
import pandas as pd
import set_path
import supp.support_load as sl

In [2]:
dfs, dfs_name, dfs_export_date = sl.load_pickle()
dfs_export_date

Pickle database loaded.
C:\Users\Stoja\OneDrive\Documents\diplomka\scr\data\dfs_complete.pickle
Applied preprocessing: merge_on_jones
Applied preprocessing: remove_jones_duplicates

'2024-10-11'

In [3]:
iton, ntoi = sl.get_name_dicts(dfs_name)
pd.DataFrame(dfs_name)

                                   0
0                         df_general
1                            df_tomb
2                  df_tomb_king_name
3                     df_tomb_chapel
4                     df_tomb_osiris
5            df_tomb_statue_material
6                        df_tomb_dim
7                            df_name
8                          df_person
9         df_person_working_activity
10           df_shaft_burial_chamber
11              df_shaft_sarcophagus
12                   df_shaft_coffin
13            df_tomb_shaft_relation
14       df_shaft_burial_chamber_dim
15                           df_body
16                    df_body_housed
17                    df_source_type
18                          df_notes
19               df_current_location
20                         df_dating
21                      df_reference
22                  df_bib_reference
23                     df_kings_info
24              df_coffin_decoration
25             df_general_coffin_dec
26         df_sarcophagus_decoration
27        df_general_sarcophagus_dec
28                     df_attributes
29             df_general_attributes
30            df_attributes_position
31                      df_equipment
32              df_general_equipment
33             df_equipment_material
34               df_family_relations
35                         df_titles
36         df_titles_other_reference
37                 df_titles_general
38                   df_person_title
39                     df_false_door
40      df_false_door_family_members
41  df_false_door_titles_highlighted
42           df_false_door_festivals
43             df_false_door_general